name: Compaile-and-run
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: 'latest'
        
      - name: Compaile Java Program
        run: javac HelloWorld.java

      - name: Run Java program 
        run: java HelloWorld
      
      
